## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/Vacation_Search.csv")
vacation_df.head()

City_ID          City Country  Max Temp Current Description      Lat  \
0        3          Aksu      CN     88.93              Clouds  41.1231   
1        5         Ambon      ID     77.14              Clouds  -3.6954   
2       11  Puerto Ayora      EC     78.76              Clouds  -0.7393   
3       12     Hithadhoo      MV     81.07                Rain  -0.6000   
4       13        Atuona      PF     78.15              Clouds  -9.8000   

        Lng                 Hotel Name  
0   80.2644       Pudong Holiday Hotel  
1  128.1814       Swiss-Belhotel Ambon  
2  -90.3518  Finch Bay Galapagos Hotel  
3   73.0833          Scoop Guest House  
4 -139.0333                Villa Enata

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
<dt>Current Description</dt><dd>{Current Description} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
vacation_df.head()

City_ID          City Country  Max Temp Current Description      Lat  \
0        3          Aksu      CN     88.93              Clouds  41.1231   
1        5         Ambon      ID     77.14              Clouds  -3.6954   
2       11  Puerto Ayora      EC     78.76              Clouds  -0.7393   
3       12     Hithadhoo      MV     81.07                Rain  -0.6000   
4       13        Atuona      PF     78.15              Clouds  -9.8000   

        Lng                 Hotel Name  
0   80.2644       Pudong Holiday Hotel  
1  128.1814       Swiss-Belhotel Ambon  
2  -90.3518  Finch Bay Galapagos Hotel  
3   73.0833          Scoop Guest House  
4 -139.0333                Villa Enata

In [5]:
# 4a. Add a marker layer for each city to the map.
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)


# 4b. Display the figure
fig


Figure(layout=FigureLayout(height='420px'))

In [6]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df["City"] == "Half Moon Bay"]
vacation_end = vacation_df.loc[vacation_df["City"] == "Half Moon Bay"]
vacation_stop1 = vacation_df.loc[vacation_df["City"] == "Pacifica"]
vacation_stop2 = vacation_df.loc[vacation_df["City"] == "Clearlake"] 
vacation_stop3 = vacation_df.loc[vacation_df["City"] == "Ukiah"] 

In [7]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start[["Lat", "Lng"]].to_numpy()
end = vacation_end[["Lat", "Lng"]].to_numpy()
stop1 = vacation_stop1[["Lat", "Lng"]].to_numpy()
stop2 = vacation_stop2[["Lat", "Lng"]].to_numpy()
stop3 = vacation_stop3[["Lat", "Lng"]].to_numpy()

In [8]:
print(start)
print(end)
print(stop1)
print(stop2)
print(stop3)

[[  37.4636 -122.4286]]
[[  37.4636 -122.4286]]
[[  37.6138 -122.4869]]
[[  38.9582 -122.6264]]
[[  39.1502 -123.2078]]


In [9]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

start = (37.4636, -122.4286)
end = (37.4636, -122.4286)
stop1 = (37.6138, -122.4869)
stop2 = (38.9582, -122.6264)
stop3 = (39.1502, -123.2078)

waypoints = [stop1, stop2, stop3]

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=2.0)

directions_layer = gmaps.directions_layer(start, end, waypoints=waypoints, travel_mode='DRIVING')

fig.add_layer(directions_layer)


# 4b. Display the figure
fig


Figure(layout=FigureLayout(height='420px'))

In [10]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start,
                         vacation_stop1,
                         vacation_stop2,
                         vacation_stop3]
                         ,ignore_index=True)
itinerary_df

City_ID           City Country  Max Temp Current Description      Lat  \
0      303  Half Moon Bay      US     84.15              Clouds  37.4636   
1      275       Pacifica      US     83.73              Clouds  37.6138   
2      309      Clearlake      US     77.81              Clouds  38.9582   
3      435          Ukiah      US     80.53               Clear  39.1502   

        Lng                                         Hotel Name  
0 -122.4286                    The Ritz-Carlton, Half Moon Bay  
1 -122.4869  Pacifica Lighthouse, Trademark Collection by W...  
2 -122.6264  Americas Best Value Inn & Suites Clearlake Win...  
3 -123.2078                                  Hampton Inn Ukiah

In [11]:
itinerary_df.dtypes

City_ID                  int64
City                    object
Country                 object
Max Temp               float64
Current Description     object
Lat                    float64
Lng                    float64
Hotel Name              object
dtype: object

In [14]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
mark_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

# 11a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 30.0), zoom_level=2.0)

marker_layer = gmaps.marker_layer(locations, info_box_content=mark_info)

fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))